Dynamic/LessonPediaProject/generic_apps/urls.py
from django.urls import path
from . import views as general_views

urlpatterns = [
    path("", general_views.landing_page, name="landing_page"),
    path("reviews/", general_views.reviews, name="reviews"),
    path("funTest/", general_views.fun_test, name="fun_test"),
    path("privacy/", general_views.privacy, name="privacy"),
    path("terms/", general_views.terms, name="terms"),
    path('tutor_sign_up/', general_views.tutor_sign_up, name='tutor_sign_up'),
    path('client_sign_up/', general_views.client_sign_up, name='client_sign_up'),
    path('app_admin_sign_up/', general_views.app_admin_sign_up, name='app_admin_sign_up'),
    # path('delete_user/<int:user_id>/', delete_user, name='delete_user'),
    path("about_us/developers/", general_views.about_us, name="aboutUs"),


    path("api/get_tutors_reports/", general_views.get_tutors_reports, name="get_tutors_reports"),
    path("api/get_clients_reports/", general_views.get_clients_reports, name="get_clients_reports"),
]

Dynamic/LessonPediaProject/lessonpedia/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .admin import lessonPedia_admin_site


urlpatterns = [
    path('lessonpedia/', lessonPedia_admin_site.urls),
    path('admin/', admin.site.urls),
    # path('auth/', include('social_django.urls', namespace='social')),
    path("", include("generic_apps.urls")),
    path("client/", include('client.urls')),
    path("tutor/", include('tutor.urls')),
    path("appAdmin/", include('app_admin.urls')),
    path('api-auth/', include('rest_framework.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Dynamic/LessonPediaProject/tutor/urls.py
from django.urls import path
from .  import views


urlpatterns = [
    path('login/', views.tutor_login, name='tutor_login'),
    path('dashboard/', views.tutor_dashboard, name='tutor_dashboard'),
    path('logout/', views.tutor_logout, name='tutor_logout'),
    path('profile/', views.tutor_profile,name='tutor_profile' ),
    path('tutors/', views.view_tutors, name='view_tutors'),
    path('searchTutors/', views.search_tutors, name='search_tutors'),
    path('tutorDetail/<int:tutor_id>/', views.tutor_detail, name='tutor_detail'),
    path('emailTutor/<int:tutor_id>/', views.email_tutor, name='email_tutor'),
    path('quizGuide/', views.quiz_guide, name='quiz_guide'),
    path('quiz/', views.tutor_quiz, name='tutor_quiz'),
    path('adminSupport/', views.admin_support, name='admin_support'),
    path('suspendTutor/<int:tutor_id>/', views.suspend_tutor, name='suspend_tutor'),
    path('blockTutor/<int:tutor_id>/', views.block_tutor, name='block_tutor'),
    path('deleteSchedule/<int:schedule_id>/', views.delete_schedule, name='delete_schedule'),
    path('uploadDocs/', views.upload_docs, name='upload_docs'),
    path('changePassword/', views.change_password, name='change_password'),
    path('moreUpdate/', views.more_update, name='more_update'),
    path('addSubject/', views.add_subject, name='add_subject'),
    path('updateSubject/<int:subject_id>/', views.update_subject, name='update_subject'),
    path('deleteSubject/<int:subject_id>/', views.delete_subject, name='delete_subject'),
    path('createContract/<int:tutor_id>/', views.create_contract, name='create_contract'),
    path('updateContractStatus/<contract_code>/', views.update_contract_status, name='update_contract_status'),
    path('terminate_contract', views.terminate_contract, name='terminate_contract'),
    path('reportAbuse/', views.report_abuse, name='report_abuse'),
    # path('funTest/', views.fun_test, name='fun_test'),
    path('forgotPassword/', views.forgot_password, name='tutor_forgot_password'),
    path('ResetToken/', views.confirm_password_reset_token, name='tutor_reset_token'),
    path('resetPassword/', views.reset_password, name='tutor_reset_password'),
]

Dynamic/LessonPediaProject/generic_apps/forms.py
from typing import Any
from django import forms
from django.contrib.auth.forms import UserCreationForm
from client.models import Client
from tutor.models import Tutor
from app_admin.models import AppAdmin


class ClientRegisterForm(UserCreationForm):
    """Register form for client"""
    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)
        self.fields['email'].widget.attrs.update(
            {
                'placeholder': 'Enter your email',
            }
        )
        self.fields['username'].widget.attrs.update(
            {
                'placeholder': 'Enter username',
            }
        )
        self.fields['password1'].widget.attrs.update(
            {
                'placeholder': '********',
            }
        )
        self.fields['password2'].widget.attrs.update(
            {
                'placeholder': '********',
            }
        )

    class Meta:
        model = Client
        fields = ['username', 'email', 'password1', 'password2']


class TutorRegisterForm(UserCreationForm):
    """this class abstracts the tutor registration model"""
    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)
        self.fields['username'].widget.attrs.update({
            'name':'username',
            'placeholder':'enter username'
        })

        self.fields['email'].widget.attrs.update({
            'name':'email',
            'placeholder':'enter email'
        })

        self.fields['password1'].widget.attrs.update({
            'name':'password',
            'placeholder':'********',
            'id': 'pass'
        })

        self.fields['password2'].widget.attrs.update({
            'name':'confirm_password',
            'placeholder':'********',
            'id':'con_pass'
        })

        self.fields['primary_subject'].widget.attrs.update({
            'id': 'high_qual',
            'placeholder': 'first core subject'
        })

        self.fields['highest_qualification'].widget.attrs.update({
            
        })

    class Meta:
        model = Tutor
        fields = [
            'username', 'email', 'password1', 'password2', 'primary_subject', 'highest_qualification'
        ]


class AppAdminRegisterForm(UserCreationForm):
    """Register form for AppAdmin"""
    class Meta:
        model = AppAdmin
        fields = ['username', 'email', 'password1', 'password2']
    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)
        self.fields['email'].widget.attrs.update(
            {
                'placeholder': 'Enter your email',
            }
        )
        self.fields['username'].widget.attrs.update(
            {
                'placeholder': 'Enter username',
            }
        )
        self.fields['password1'].widget.attrs.update(
            {
                'placeholder': '********',
            }
        )
        self.fields['password2'].widget.attrs.update(
            {
                'placeholder': '********',
            }
        )

Dynamic/LessonPediaProject/tutor/forms.py
from django import forms
from django_countries.fields import countries
from django_flatpickr.widgets import DatePickerInput
from .models import Tutor, Day, TimeSlot


class TutorScheduleForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # Change the default label for empty option in dropdowns
        self.fields['day'].empty_label = 'Select Day'
        self.fields['from_hour'].empty_label = 'Select Time'
        self.fields['to_hour'].empty_label = 'Select Time'

        self.fields['day'].widget.attrs['class'] = 'day_field'
        self.fields['day'].widget.attrs['id'] = 'dayField'

        self.fields['from_hour'].widget.attrs['class'] = 'from_hour'
        self.fields['from_hour'].widget.attrs['id'] = 'fromHour'

        self.fields['to_hour'].widget.attrs['class'] = 'to_hour'
        self.fields['to_hour'].widget.attrs['id'] = 'toHour'

    class Meta:
        model = TimeSlot
        fields = ['day', 'from_hour', 'to_hour']


class TutorUpdateForm(forms.ModelForm):
    """Tutor update form"""
    def save(self, commit=True):
        instance = super().save(commit=False)
        if commit:
            instance.save()

        return instance
    institution_type = forms.ChoiceField(
        choices=[
        ('--select one--', '--select one--'),
        ('University', 'University'),
        ('Polytechnic', 'Polytechnic'),
        ('College Of Education', 'College Of Education'),
        ('Vocational', 'Vocational'),
        ('Others', 'Others'),

        ],
        widget=forms.Select(attrs={
            'class': 'no_outline',
            'id': 'institution_type',
        })
    )

    institution = forms.CharField(
        required=True,
        widget=forms.TextInput(attrs={
            'id': 'institution',
            'placeholder': 'top-most institution attended',
        })
    )

    discipline = forms.CharField(
        required=True,
        widget=forms.TextInput(attrs={
            'id': 'dis',
            'placeholder': 'What\'s your discipline?',
        })
    )

    highest_qualification = forms.ChoiceField(
        choices=[
            ('--select one--', '--select one--'),
            ('Phd', 'Phd'),
            ('Msc', "Msc"),
            ('BED', 'BED'),
            ('BSC', 'BSC'),
            ('BENG', 'BENG'),
            ('HND', 'HND'),
            ('OND', 'OND'),
            ('NCE', 'NCE'),
            ('SSCE', 'SSCE'),
            ('Others', 'Others')
        ],
        widget=forms.Select(attrs={
            'id': 'qual',
        })
    )

    result = forms.ChoiceField(
        choices=[
            ('', '-- Select One --'),
            ('First Class', 'First Class'),
            ('Distinction', 'Distinction'),
            ('Second Class Upper', 'Second Class Upper'),
            ('Upper credit', 'Upper credit'),
            ('Second Class Lower', 'Second Class Lower'),
            ('Lower credit', 'Lower credit'),
            ('Others', 'Others'),
        ],
        widget=forms.Select(attrs={
            'class': 'no_outline',
            'id': 'degree_class',
        })
    )

    employment_status = forms.ChoiceField(
        choices=[
            ('', '--select one--',),
            ('Employed', 'Employed'),
            ('Self Employed', 'Self Employed'),
            ('Unemployed', 'Unemployed'),
        ],
        widget=forms.Select(attrs={
            'class': 'no_outline',
            'id': 'empStat',
        })
    )

    employment_type = forms.ChoiceField(
        choices=[
        ('--select one--', '--select one--'),
        ('Full Time', 'Full Time'),
        ('Part Time', 'Part Time'),
        ('Freelance', 'Freelance'),
        ('Others', 'Others'),
        ],
        required=False,
        widget=forms.Select(attrs={
            'class': 'no_outline',
            'id': 'employmentStat',
        })
    )
#     date_of_birth = forms.DateField(
#     widget=DatePickerInput(
#         attrs={
#             'class': 'no_outline',
#             'id': 'dob',
#             'placeholder': 'Format: (MM/DD/YYYY)',
#         }
#     )
# )

    nationality = forms.CharField(
        widget=forms.TextInput(attrs={
            'class': 'nationality',
        })
    )


    # nationality = forms.CharField(
    #     widget=forms.CharField(choices=countries),
    #     required=True
    # )



    # state_of_residence = forms.ChoiceField(
    #     choices=[
    #         ('', '- Select -'),
    #         ('Abia', 'Abia'), ('Adamawa', 'Adamawa'), ('AkwaIbom', 'AkwaIbom'),
    #         ('Anambra', 'Anambra'), ('Bauchi', 'Bauchi'), ('Bayelsa', 'Bayelsa'),
    #         ('Benue', 'Benue'), ('Borno', 'Borno'), ('Cross River', 'Cross River'),
    #         ('Delta', 'Delta'), ('Ebonyi', 'Ebonyi'), ('Edo', 'Edo'),
    #         ('Ekiti', 'Ekiti'), ('Enugu', 'Enugu'), ('FCT', 'FCT'),
    #         ('Gombe', 'Gombe'), ('Imo', 'Imo'), ('Jigawa', 'Jigawa'),
    #         ('Kaduna', 'Kaduna'), ('Kano', 'Kano'), ('Katsina', 'Katsina'),
    #         ('Kebbi', 'Kebbi'), ('Kogi', 'Kogi'), ('Kwara', 'Kwara'),
    #         ('Lagos', 'Lagos'), ('Nasarawa', 'Nasarawa'), ('Niger', 'Niger'),
    #         ('Ogun', 'Ogun'), ('Ondo', 'Ondo'), ('Osun', 'Osun'),
    #         ('Oyo', 'Oyo'), ('Plateau', 'Plateau'), ('Rivers', 'Rivers'),
    #         ('Sokoto', 'Sokoto'), ('Taraba', 'Taraba'), ('Yobe', 'Yobe'),
    #         ('Zamfara', 'Zamafara'),
    #     ],
    #     widget=forms.Select(attrs={
    #         'class': 'select-option no_outline',
    #         'id': 'state',
    #         'onchange': 'toggleLGA(this);',
    #     })
    # )

    # state_of_residence = forms.CharField(
    #     widget=forms.TextInput(attrs={
    #         'class': 'state_of_residence',
    #         'id': 'state',
    #     })
    # )

    highest_qualification_cert = forms.FileField(
        required=False,
        widget=forms.FileInput(attrs={
            'id': 'cert',
            'placeholder': 'upload certificate',
            'class': 'file_button'
        })
    )

    cv_id = forms.FileField(
        required=False,
        widget=forms.FileInput(attrs={
            'id': 'cv',
            'placeholder': 'upload cv',
            'class': 'file_button'
        })
    )

    profile_picture = forms.ImageField(
        widget=forms.FileInput(attrs={
            'id': 'pic',
            'placeholder': 'upload profile picture',
            'class': 'file_button'
        })
    )

    gender = forms.ChoiceField(
        choices=[
            ('', '- Select -'),
            ('Male', 'Male'),
            ('Female', 'Female'),
        ],
        widget=forms.Select(attrs={
            'id': 'gender2',
            'class': 'no_outline',
        })
    )
    open_to_work = forms.ChoiceField(
        choices=Tutor.open_to_work_choice,
        widget=forms.Select(attrs={
            'id': 'open_to_work',
            'class': 'no_outline',
        })
    )


    class Meta:
        model = Tutor
        fields = [
                'first_name', 'last_name', 'others', 'phone_number', 'highest_qualification',
                'area_of_specialization', 'discipline', 'employment_status','employment_type','nationality',
                'state_of_residence', 'institution_type', 'institution', 'result',
                'residential_address', 'cv_id', 'highest_qualification_cert', 'profile_picture', 'gender', 'open_to_work'

            ]
        widgets = {
            'first_name': forms.TextInput(attrs={
                'name': 'first_name',
                'placeholder': 'enter first name',
                'id': 'first_name',
                'autocomplete': 'on'

            }),
            'last_name': forms.TextInput(attrs={
                'name': 'last_name',
                'placeholder': 'enter last name',
                'id': 'last_name',
                'autocomplete': 'on',
            }),
            'others': forms.TextInput(attrs={
                'name': 'others',
                'placeholder': 'enter other names',
                'required': False,
                'id': 'others',
                'autocomplete': 'on',
            }),
            'phone_number': forms.TextInput(attrs={
                'name': 'phone_number',
                'placeholder': '+234xxxxxxxxxx',
                'id': 'phone_number'
            }),

            'area_of_specialization': forms.TextInput(attrs={
                'name': 'area_of_specialization',
                'placeholder': 'enter area of specialization',
                'id': 'area_of_specialization',
                'required': False,
                'autocomplete': 'on',
            }),
            'residential_address': forms.TextInput(attrs={
                'name': 'residential_address',
                'placeholder': 'enter residential address',
                'id': 'residential_address',
                'autocomplete': 'on',
            }),
            'state_of_residence': forms.TextInput(attrs={
                'name': 'state_of_residence',
                'placeholder': 'enter state of residence',
                'id': 'state',
                'autocomplete': 'on',
            })
        }

Dynamic/LessonPediaProject/generic_apps/templates/generic_apps/client_sign_up.html
{% extends "generic_apps/base.html" %}
{% load static %}
{% block head %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'styles/register.css' %}">
    <link rel="stylesheet" href="{% static 'styles/client_reg.css' %}">
    <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
    <script src="{% static 'script/register.js' %}"></script>
    <script src="{% static 'script/signUp.js' %}"></script>
    <title>Client - SignUp</title>
{% endblock head %} 
<body>
{% block content %}
<br>

    {% block pricing %}
    {% endblock pricing %}

    {% block review %}
    {% endblock review %}

    {% block nav_right %}
    {% endblock nav_right %}

    {% block signup_button %}
    {% endblock signup_button %}

   <div class="register_container">
        <div class="register_container_inputs">
            <div class="logo">
               <img src="{% static 'images/logo/logo_icon.png' %}" alt="">
            </div>
            <h3 class="register_header">
                Register As 
            </h3>
            <hr class="wide_hr">
            <div class="register_as">   
                <div class="learner tr" data-url="{% url 'client_sign_up' %}">Learner</div>
                <div class="tutor tr" data-url="{% url 'tutor_sign_up' %}">Tutor</div>
            </div>
         
            <form class="learner_form" action="{% url 'client_sign_up' %}" method="POST">
                {% csrf_token %}
                <label for="useremail">
                    Email
                </label><br>
                <!-- <input type="text" name="useremail" placeholder="enter email" id=""><br><br> -->
                {{ form.email }} <br><br>
                <label for="username">
                    Username
                </label><br>
                <!-- <input type="text" name="username" placeholder="enter username"><br><br> -->
                {{ form.username }} <br><br>
                <label for="password">
                    Password
                </label><br>
                <!-- <input type="password" name="password" placeholder="enter password" id=""><br><br> -->
                {{ form.password1 }} <br><br>
                <label for="confirm_password">
                    Confirm Password
                </label><br>
                <!-- <input type="confirm_password" name="confirm_password" placeholder="****" id="" pattern=""><br><br><br> -->
                {{ form.password2 }} <br>
                
                <br><br>
                <input type="submit" value="Sign up">
            </form>

             <!-- Tutor Form -->
             <form class="tutor_form" action="{% url 'tutor_sign_up' %}" method="POST">
                {% csrf_token %}
                <label for="useremail">
                    Email
                </label><br>
                {{ form.email }}
                <!-- <input type="text" name="useremail" placeholder="enter email" id=""> -->
                <br><br>
                <label for="username">
                    Username
                </label><br>
                {{ form.username }}
                <!-- <input type="text" name="username" placeholder="enter username"> -->
                <br><br>
                <label for="specialization">
                    Specialization | Qualification
                </label><br>
                <div class="tutor_detail">
                    <section class="specialization_container">
                        {{ form.area_of_specialization }}
                        {% comment %} <input type="text" name="specialization" placeholder="enter specialization" id="specialization"> {% endcomment %}
                        <br><br>
                    </section>
                    <section class="qualification">
                        <select name="highest_qualification" id="id_highest_qualification">
                            <option value="" selected hidden>--select one--</option>
                            <option value="Phd" {% if form.highest_qualification.value == 'Phd' %} selected {% endif %} required>Msc</option>
                            <option value="Msc" {% if form.highest_qualification.value == 'Msc' %} selected {% endif %} required>Msc</option>
                            <option value="Bsc" {% if form.highest_qualification.value == 'Bsc' %} selected {% endif %} required>Bsc</option>
                            <option value="Beng" {% if form.highest_qualification.value == 'Beng' %} selected {% endif %} required>Bsc</option>
                            <option value="HND" {% if form.highest_qualification.value == 'HND' %} selected {% endif %} required>HND</option>
                            <option value="OND" {% if form.highest_qualification.value == 'OND' %} selected {% endif %} required>OND</option>
                            <option value="NCE" {% if form.highest_qualification.value == 'NCE' %} selected {% endif %} required>OND</option>
                            <option value="O-Level" {% if form.highest_qualification.value == 'O-Level' %} selected {% endif %} required>O-Level</option>
                            <option value="Others" {% if form.highest_qualification.value == 'Others' %} selected {% endif %} required>Other</option>
                        </select>               
                    </section>
                </div>
                <label for="password">
                    Password
                </label><br>
                {{ form.password1 }}
                <!-- <input type="password" name="password" placeholder="enter password" id=""> -->
                <br><br>
                <label for="confirm_password">
                    Confirm Password
                </label><br>
                {{ form.password2 }}
                <!-- <input type="confirm_password" name="confirm_password" placeholder="****" id="" pattern=""> -->
                <br><br><br>
                <br><input id="registerBtn" type="submit" value="Sign up">
            </form><br>

            {% if messages %}
                {% for message in messages  %}
                    <div class='error'>
                        <p class="flash_error">{{ message }}</p>
                    </div>
                {% endfor %}
            {% endif %}
            
            <br>
            <center><p class="change_color hide_signup">or signup with</p></center>
            <div class="link_box_container">
                <div class="link_box">
                    <a href=""><img src="{% static 'images/socialLinks/google.png' %}" alt=""></a>
                </div>
                <div class="link_box">
                    <a href=""><img src="{% static 'images/socialLinks/facebook.png' %}" alt=""></a>
                </div>
                <div class="link_box">
                    <a href=""><img src="{% static 'images/socialLinks/github.png' %}" alt=""></a>
                </div>  
            </div>
            <div class="ending">
                <center><p class="change_color">Already have an account? <span><a href="{% url 'client_signIn' %}">Login here</a></span></p></center>
            </div>
        </div>
   </div>
</div>
<br><br>
{% endblock content %}
</body>

Dynamic/LessonPediaProject/generic_apps/templates/generic_apps/login.html
{% extends 'generic_apps/base.html' %}
{% load static %}

{% block head %}  <link rel="stylesheet" href="{% static "../css/login.css" %}">{% endblock head %}
  
  {% block title %}Login{% endblock title %}
    {% block signup_button %}{% endblock signup_button %}
    {% block content %}
        <div class="login_container">
            <div class="login_container_inputs">
                <div class="logo">
                <img src="{% static "../images/socialLinks/github.png" %}" alt="">
                </div>
                <h3 class="login_header">
                    Login
                </h3>
                <form action="#">
                    <label for="useremail">
                        UserName or Email
                    </label><br>
                    <input type="text" name="useremail" placeholder="enter username or email" id=""><br><br><br>
                    <label for="password">
                        Password
                    </label><br>
                    <input type="password" name="password" placeholder="********" id="" pattern=""><br>
                    <h5 class="forgetPasscode">Forget password</h5><br><br><br>
                    <input type="submit" value="Sign in">
                </form><br>
                <p><center class="change_color">or continue with</center></p>
                <div class="link_box_container">
                    <div class="link_box">
                        <a href="{% static "" %}"><img src="{% static "../images/socialLinks/google.png" %}" alt=""></a>
                    </div>
                    <div class="link_box">
                        <a href="{% static "" %}"><img src="{% static "../images/socialLinks/facebook.png" %}" alt=""></a>
                    </div>
                    <div class="link_box">
                        <a href="{% static "" %}"><img src="{% static "../images/socialLinks/github.png" %}" alt=""></a>
                    </div>  
                </div>
                <div class="ending">
                    <center><p class="change_color">Don't have account account yet? <span><a href="{% static "" %}">Register here</a></span></p></center>
                </div>
            </div>
        </div>
    {% endblock content %}
    <br><br>

Dynamic/LessonPediaProject/generic_apps/templates/generic_apps/sign_up.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'styles/register.css' %}">
    <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
    <script src="{% static 'script/register.js' %}"></script>
    <title>Register</title>
</head>
<body>
   <div class="register_container">
        <div class="register_container_inputs">
            <div class="logo">
               <img src="{% static 'images/socialLinks/github.png' %}" alt="">
            </div>
            <h3 class="register_header">
                Register As 
            </h3>
            <hr class="wide_hr">
            <div class="register_as">   
                <div class="learner tr">Learner</div>
                <div class="tutor tr">Tutor</div>
            </div>
         
            <form class="learner_form" method='post' action="{% url 'client_sign_up' %}">
                {% csrf_token %}
                <label for="useremail">
                    Email
                </label><br>
                {{ form.email }}
                <br><br>
                <label for="username">
                    Username
                </label><br>
                {{ form.username }}
                <br><br>

                <label for="password">
                    Password
                </label><br>
                {{ form.password1 }}

                <br><br>
                <label for="confirm_password">
                    Confirm Password
                </label><br>
                {{ form.password2 }}

                <br><br><br>
                <input type="submit" value="Sign up">
            </form>

            <!-- Tutor Form -->
            <form class="tutor_form" method="post" action="{% url 'tutor_sign_up' %}">
                {% csrf_token %}
                <label for="useremail">
                    Email
                </label><br>
                {% comment %} <input type="text" name="useremail" placeholder="enter email" id=""> {% endcomment %}
                {{ form.email }}

                <br><br>
                <label for="username">
                    Username
                </label><br>
                {% comment %} <input type="text" name="username" placeholder="enter username"> {% endcomment %}
                {{ form.username }}

                <br><br>
                <label for="specialization">
                    Specialization | Qualification
                </label><br>
                <div class="tutor_detail">
                    <section class="specialization_container">
                        {% comment %} <input type="text" name="specialization" placeholder="enter specialization" id="specialization">
                        {{ form.area_of_specialization }} {% endcomment %}
                    </section>

                    <section class="qualification">
                        <select name="highest_qualification" id="id_highest_qualification">
                            <option value="" selected hidden>Highest Qualification</option>
                            <option value="Msc" {% if form.highest_qualification.value == 'Msc' %} selected {% endif %} required>Msc</option>
                            <option value="Bsc" {% if form.highest_qualification.value == 'Bsc' %} selected {% endif %} required>Bsc</option>
                            <option value="HND" {% if form.highest_qualification.value == 'HND' %} selected {% endif %} required>HND</option>
                            <option value="OND" {% if form.highest_qualification.value == 'OND' %} selected {% endif %} required>OND</option>
                            <option value="O-Level" {% if form.highest_qualification.value == 'O-Level' %} selected {% endif %} required>O-Level</option>
                            <option value="Other" {% if form.highest_qualification.value == 'Other' %} selected {% endif %} required>Other</option>
                        </select>               
                    </section>
                </div>
                <label for="password">
                    Password
                </label><br>
                {% comment %} <input type="password" name="password" placeholder="enter password" id=""> {% endcomment %}
                {{ form.password1 }}
                <br><br>
                <label for="confirm_password">
                    Confirm Password
                </label><br>
                {% comment %} <input type="confirm_password" name="confirm_password" placeholder="********" id="" pattern=""> {% endcomment %}
                {{ form.password2 }}

                <br><br><br>
                <br><input type="submit" value="Sign up">
            </form><br>
            <center><p class="change_color hide_signup">or signup with</p></center>
            <div class="link_box_container">
                <div class="link_box">
                    <a href=""><img src="{% static 'images/socialLinks/google.png' %}" alt=""></a>
                </div>
                <div class="link_box">
                    <a href=""><img src="{% static 'images/socialLinks/facebook.png' %}" alt=""></a>
                </div>
                <div class="link_box">
                    <a href=""><img src="{% static 'images/socialLinks/github.png' %}" alt=""></a>
                </div>  
            </div>
            <div class="ending">
                <center><p class="change_color">Already have an account? <span><a href="">Login here</a></span></p></center>
            </div>
        </div>
   </div>
    
</body>
</html>